# General Configuration
namespace: webhook
app:
  name: validate-app-label 
  image: <image:tag>
  replicaCount: 1

# Service Configuration
service:
  port: 443

# Validating Webhook Configuration
webhook:
  path: "/validate"
  rules:
    apiGroups: ["*"]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations: ["CREATE"]
