apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      serviceAccountName: {{ .Values.namespace }}
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}
        args: ["/certs/tls.crt", "/certs/tls.key"]
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: {{ .Values.app.name }}-tls
