apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-tls
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Files.Get "certs/webhook.crt" | b64enc }}
  tls.key: |
    {{ .Files.Get "certs/webhook.key" | b64enc }}
